Update script to support a config file.
RoarkGit/Pedal-Mapper pull request #1
Opened 2024-07-17 02:34 UTC by Rambomst

- Update script to load key mappings from config files rather than being hard coded.
- Updated readme to support new config changes.
- Added default config json file.

2024-07-17 12:52 UTC, RoarkGit requested changes
Overall looks good, just some minor nitpicky things. Thanks for the contribution!

2024-07-17 12:52 UTC, RoarkGit commented on config.default.json
> +    {
nit: These curly brace sections should be indented.

2024-07-17 12:52 UTC, RoarkGit commented on pedal_mapper.py
> +            mods = [getattr(e, mod) for mod in combo["mods"]]
It would be convenient if "mods" could be optional; I tried testing by adding a key to the config that didn't have "mods" set and it didn't run.

2024-07-17 12:52 UTC, RoarkGit commented on README.md
> +    {
nit: This should be indented.

2024-07-17 22:19 UTC, Rambomst commented
@RoarkGit All of those issues should be resolved, let me know if there is anything else you would like changed/added.

:)

2024-07-18 10:31 UTC, Rambomst commented
I updated the README to include more systemd information

2024-07-18 12:49 UTC, RoarkGit commented
> I updated the README to include more systemd information

Thanks, I was going to do that as well but you beat me to it!

2024-07-18 12:49 UTC, merged